# Generated by Django 4.2 on 2024-11-07 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemservice",
            options={"verbose_name_plural": "Stocks"},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name_plural": "CompanyProfile"},
        ),
        migrations.AlterModelOptions(
            name="sale",
            options={"verbose_name_plural": " invoices"},
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"verbose_name_plural": " invoiceItems"},
        ),
    ]
